#!/bin/bash

file="storage"
read -r numInStorage < $file
temp=$(( $numInStorage + 8 ))

if (( $temp < 100 )) 
then
    echo $temp > $file
    echo "from producer: current total is $temp"
    ./consumer
else
    echo "from producer: Now I will take a rest!"
fi

